### ISSUE TITLE
example incorrect

### ISSUE THREAD

**Issue by nir-moon** [marmelab/ng-admin#1163]
after adding :

```js
post.showView().fields([
    nga.field('title'),
    nga.field('body', 'text'),
    nga.field('userId', 'reference')
        .targetEntity(user)
        .targetField(nga.field('username'))
        .label('User'),
    nga.field('comments', 'referenced_list')
        .targetEntity(nga.entity('comments'))
        .targetReferenceField('postId')
        .targetFields([
            nga.field('email'),
            nga.field('name')
        ])
        .sortField('id')
        .sortDir('DESC'),
]);

//As a side note, you can see that it's possible to create a reference to a non-existent entity (nga.entity('comments) creates the related entity for the occasion).
```

getting error:

```
angular.js:12783 Error: Unable to find entity "comments"
    at e.value (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:14:3511)
    at pre (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:16:4339)
    at http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:25:5744
    at ae (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:25:5801)
    at g (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:24:31435)
    at s (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:24:27816)
    at http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:24:27345
    at link (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:15:29843)
    at http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:25:5744
    at ae (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:25:5801) <ma-referenced-list-column field="::field" datastore="::datastore" class="ng-scope ng-isolate-scope">(anonymous function) @ angular.js:12783(anonymous function) @ angular.js:9535ae @ angular.js:9081g @ angular.js:8545s @ angular.js:7965(anonymous function) @ angular.js:7845link @ maColumn.js:64(anonymous function) @ angular.js:9073ae @ angular.js:9079g @ angular.js:8566s @ angular.js:7965g @ angular.js:8561s @ angular.js:7965g @ angular.js:8561s @ angular.js:7965s @ angular.js:7968g @ angular.js:8561s @ angular.js:7965(anonymous function) @ angular.js:7845r @ angular.js:7983l @ angular.js:8593(anonymous function) @ Compile.js:16$digest @ angular.js:16203(anonymous function) @ angular.js:16398i @ angular.js:5754(anonymous function) @ angular.js:6031
10angular.js:12783 TypeError: Cannot read property 'isReadOnly' of undefined
    at o (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:15:28864)
    at link (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:15:29717)
    at http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:25:5744
    at ae (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:25:5801)
    at g (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:24:31621)
    at s (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:24:27816)
    at g (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:24:31570)
    at s (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:24:27816)
    at http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:24:27345
    at r (http://localhost:8080/node_modules/ng-admin/build/ng-admin.min.js:24:28305) <ma-column field="::field" entry="::entry" entity="::entity" datastore="datagrid.datastore" class="ng-isolate-scope">
```

**Comment by suricactus** [comment]
I have encountered the same problem and I've found a fix: You have to add the entity to the admin instance:
```
    var comments = nga.entity('comments');
    admin.addEntity(comments);
```

**Comment by fzaninotto** [comment]
@suricactus isn't just a fix, it's the only way this is supposed to work 😉
