### ISSUE TITLE
Customize menubar

### ISSUE THREAD

**Issue by collonmadepvtltd** [marmelab/ng-admin#1175]
I have customize header with :

`admin.header(headerTemplate);`

Now I want to customize menubar so I wrote :

```
var menuTemplate =
      '<ul class="sidebar-menu" id="side-menu"  compile="menu.template()">>'+
        '<li class="header">MAIN NAVIGATION</li>'+
        '<li class="entities-repeat treeview"  ng-repeat="(key, menu) in ::menu.children()" data-menu-id="{{ ::menu.uuid }}" compile="menu.template()">'+



          '<a ng-if="::menu.hasChild()" ng-click="toggleMenu(menu)" ng-class="::{\'active\': menu.isActive(path)}">'+
                    '<span compile="::menu.icon()"><span class="glyphicon glyphicon-list"></span></span>'+
                    '{{ menu.title() | translate }}'+
                    '<span class="pull-right-container ng-class="::{\'glyphicon-menu-down\': isOpen(menu), \'glyphicon-menu-right\': !isOpen(menu) }"></span>'+
          '</a>'+

          '<a ng-if="::menu.hasChild()" ng-click="toggleMenu(menu)" ng-class="::{\'active\': menu.isActive(path)}">'+
                    '<span compile="::menu.icon()"><span class="glyphicon glyphicon-list"></span></span>'+
                    '{{ menu.title() | translate }}'+
                    '<span  ng-class="::{\'glyphicon-menu-down\': isOpen(menu), \'glyphicon-menu-right\': !isOpen(menu) }"></span>'+
          '</a>'+

          
          '<ul  ng-if="::menu.hasChild()"  ng-class="::{\'collapsed\': !isOpen(menu) }"  class="treeview-menu">'+
            '<li class="active" ng-repeat="menu in ::menu.children()" data-menu-id="{{ ::menu.uuid }}" compile="menu.template()">'+
                '<a href="#{{menu.link()}}" ng-click="activateLink(menu)" ng-class="::{\'active\': menu.isActive(path)}">'+
                   '<span compile="::menu.icon()"><span class="glyphicon glyphicon-list"></span></span>'+
                  '{{ menu.title() | translate }}'+
                '</a>'+
              '</li>'+
          '</ul>'+

        '</li>'+
       '</ul>'
       ;

admin.menu(menuTemplate);
```

This gives error :

```
TypeError: r.menu.children is not a function
    at link (http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:18:20441)
    at http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:25:5744
    at ae (http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:25:5801)
    at g (http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:24:31621)
    at s (http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:24:27816)
    at s (http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:24:27833)
    at s (http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:24:27833)
    at s (http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:24:27833)
    at http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:24:27345
    at http://localhost:3001/node_modules/ng-admin/build/ng-admin.min.js:13:23860 <ma-menu-bar menu="::appController.menu" class="ng-isolate-scope">
```

My Layout template is :

```
var layoutTemplate ='<div id="wrapper"  class="wrapper">'+
    '<header class="main-header">'+
        '<!-- Logo -->'+
        '<a href="#" ng-click="appController.displayHome()" class="logo">'+
          '<!-- mini logo for sidebar mini 50x50 pixels -->'+
          '<span class="logo-mini"><b>ST</b>A</span>'+
          '<!-- logo for regular state and mobile devices -->'+
          '<span class="logo-lg">{{ ::appController.applicationName }}</span>'+
        '</a>'+
        '<span compile="::appController.header">'+
    '</header>'+
  
  '<aside class="main-sidebar" role="navigation" >'+
      
        '<section class="sidebar" role="navigation" >'+
          '<!-- Sidebar user panel -->'+
          '<div class="user-panel">'+
            '<div class="pull-left image">'+
              '<img src="js/adminlte/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">'+
            '</div>'+
            '<div class="pull-left info">'+
              '<p>Alexander Pierce</p>'+
              '<a href="#"><i class="fa fa-circle text-success"></i> Online</a>'+
            '</div>'+
          '</div>'+
          '<!-- search form -->'+
          '<form action="#" method="get" class="sidebar-form">'+
            '<div class="input-group">'+
              '<input type="text" name="q" class="form-control" placeholder="Search...">'+
                  '<span class="input-group-btn">'+
                    '<button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>'+
                    '</button>'+
                  '</span>'+
            '</div>'+
          '</form>'+

         '<ma-menu-bar menu="::appController.menu"></ma-menu-bar>'+

        '</section>'+
  '</aside>'+


    '<div id="page-wrapper">'+
      '<!-- Content Wrapper. Contains page content -->'+
      '<div class="content-wrapper">'+
        '<!-- Content Header (Page header) -->'+
        '<section class="content-header">'+
          '<h1>'+
            'Dashboard'+
            '<small>Control panel</small>'+
          '</h1>'+
          '<ol class="breadcrumb">'+
            '<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>'+
            '<li class="active">Dashboard</li>'+
          '</ol>'+
        '</section>'+

        '<!-- Main content -->'+
        '<section class="content">'+

        '<div ui-view></div>'+

        '</section>'+
      '</div>'+  
    '</div>'+
    '<div id="loader"></div>'+

'</div>';
admin.layout(layoutTemplate);
```

Header is working perfectly , but menu is giving error describes above . I will be very thankful if some one can point my mistake here . I am not very familiar with angularjs . 

Thanks.

**Comment by collonmadepvtltd** [comment]
Thank you for quick response!

I solved issue . I was putting  compile="menu.template()"> in ul element which leads it in infinite loop .
