### ISSUE TITLE
Integration with AngularStrap Popover

### ISSUE THREAD

**Issue by jamesholcomb** [marmelab/ng-admin#190]
I'm trying to integrate ng-admin into an existing Angular 1.3 app that has a dependency on AngularStrap 2.1.4.

When declaring a bs-popover like this:

        <button type="button" class="btn btn-lg btn-primary ng-scope" data-placement="bottom" bs-popover="popover">Toggle Me
        </button>
I get an error:

    TypeError: undefined is not a function
    at a (http://localhost:3000/bower_components/ng-admin/build/ng-admin.min.js:7:10936)
    at angular.module.provider.$get (http://localhost:3000/bower_components/ng-admin/build/ng-admin.min.js:7:11425)
    at PopoverFactory (http://localhost:3000/bower_components/angular-strap/dist/angular-strap.js:2628:24)
    at postLink (http://localhost:3000/bower_components/angular-strap/dist/angular-strap.js:2690:23)
    at invokeLinkFn (http://localhost:3000/bower_components/angular/angular.js:8213:9)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7722:11)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7075:13)
    at nodeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7717:24)
    at compositeLinkFn (http://localhost:3000/bower_components/angular/angular.js:7075:13)
    at publicLinkFn (http://localhost:3000/bower_components/angular/angular.js:6954:30) <button type="button" class="btn btn-lg btn-primary ng-scope" data-placement="bottom" bs-popover="popover">

Any ideas?

**Comment by jpetitcolas** [comment]
I've successfully made it work, including:

``` html
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.1.2/angular-strap.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/angular-strap/2.1.2/angular-strap.tpl.min.js"></script>
```

And configuring my view with:

``` js
post.editionView()
    // [...]
    .addField(new Field('clickme').type('template').template(function () {
        return '<button type="button" bs-popover="popover" data-title="Clicked!">Click me!</button>';
    }));
```

![image](https://cloud.githubusercontent.com/assets/688373/5721109/b977b326-9b2d-11e4-9824-9aa7a3463eed.png)

Can you try it again and let us know? 

Note we however get an error from Angularstrap:

> TypeError: Cannot read property 'toLowerCase' of undefined
    at TooltipFactory (http://cdnjs.cloudflare.com/ajax/libs/angular-strap/2.1.2/angular-strap.js:3744:43)
    at http://localhost:8000/build/ng-admin.min.js:9276:3930
    at Object.invoke (http://localhost:8000/src/javascripts/bower_components/angular/angular.js:4182:17)
    at http://localhost:8000/src/javascripts/bower_components/angular/angular.js:6482:43
    at forEach (http://localhost:8000/src/javascripts/bower_components/angular/angular.js:323:20)
    at Object.<anonymous> (http://localhost:8000/src/javascripts/bower_components/angular/angular.js:6480:13)
    at Object.invoke (http://localhost:8000/src/javascripts/bower_components/angular/angular.js:4182:17)
    at Object.enforcedReturnValue [as $get] (http://localhost:8000/src/javascripts/bower_components/angular/angular.js:4035:37)
    at Object.invoke (http://localhost:8000/src/javascripts/bower_components/angular/angular.js:4182:17)
    at http://localhost:8000/src/javascripts/bower_components/angular/angular.js:4000:37

Not sure yet from where it comes, but I'm looking on it.

**Comment by jpetitcolas** [comment]
Looking more in depth, it seems Angular UI is already included by default and conflicts with AngularStrap. If you try to use Angular UI directly with:

``` js
.addField(new Field('my-stuff').type('template').template(function () { // template() can take a function or a string
    return '<button type="button" popover-placement="top" popover="On the Top!" class="btn btn-default">Top</button>';
}));
```

It works without any error.

**Comment by jpetitcolas** [comment]
No feedback. Closing the issue. Feel free to re-open it if required.
