### ISSUE TITLE
Disable menu view and Dashboard view for entity

### ISSUE THREAD

**Issue by thangngoc89** [marmelab/ng-admin#197]
I have multiple tables like user, user_meta and I don't one to User Meta show on dashboard or menu.
Can you look into this?

**Comment by Hygor** [comment]
It does not work here:



// code
```javascript

// define all entities at the top to allow references between them
var experience = new Entity('experiences');
var promotions = new Entity('promotions').identifier(new Field('id'));
var incident   = new Entity('incident');
var tags       = new Entity('tags').readOnly(); 

// set the application entities
app.addEntity(experience)
   .addEntity(promotions)
   .addEntity(incident)
   .addEntity(tags);

tags.menuView().disable(); // this is not working, the rest of the code is just fine.

```


// error
```
 Uncaught Error: [$injector:modulerr] Failed to instantiate module myApp due to:
TypeError: undefined is not a function
    at http://localhost:3000/app.js:60:14
    at Object.invoke (http://localhost:3000/bower_components/angular/angular.js:4182:17)
    at runInvokeQueue (http://localhost:3000/bower_components/angular/angular.js:4088:35)
    at http://localhost:3000/bower_components/angular/angular.js:4097:11
    at forEach (http://localhost:3000/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost:3000/bower_components/angular/angular.js:4078:5)
    at createInjector (http://localhost:3000/bower_components/angular/angular.js:4004:11)
    at doBootstrap (http://localhost:3000/bower_components/angular/angular.js:1446:20)
    at bootstrap (http://localhost:3000/bower_components/angular/angular.js:1467:12)
    at angularInit (http://localhost:3000/bower_components/angular/angular.js:1361:5)
http://errors.angularjs.org/1.3.8/$injector/modulerr?p0=myApp&p1=TypeError%…2F%2Flocalhost%3A3000%2Fbower_components%2Fangular%2Fangular.js%3A1361%3A5)
```

**Comment by thangngoc89** [comment]
at http://localhost:3000/app.js:60:14
What is that line?
Check this too https://github.com/marmelab/ng-admin/issues/206
And which version of ng-admin are you using?

**Comment by Hygor** [comment]
that is the line:
```
       tags.menuView().disable();
```
[ line: 20; character: 12 ]

I am using the "~0.4.0" version of it and I think the order of the entities are pretty the same too.

I think that something is going wrong with the 'menuView()' function

**Comment by thangngoc89** [comment]
I think it doesn't work with ~0.4.0. Try master instead
