### ISSUE TITLE
bug with wysiwyg field named "head"

### ISSUE THREAD

**Issue by cvlmtg** [marmelab/ng-admin#273]
this is what happens when you edit an entity that have a field named "head":

![schermata 2015-02-01 alle 17 21 05](https://cloud.githubusercontent.com/assets/6401008/5992758/ebd3160e-aa36-11e4-9bc7-b64e359493a7.png)

instead of the content of that field you see that snippet of code. in show view you don't see anything but get lots of errors in the js console, like this one:

```
 TypeError: undefined is not a function
    at a.$inject (http://localhost:3000/public/vendor/ng-admin/ng-admin.min.js:4:5623)
    at http://localhost:3000/public/components/angular/angular.min.js:194:11
    at l.$get.xa.(anonymous function) [as value] (http://localhost:3000/public/components/angular/angular.min.js:59:175)
    at hb.functionCall (http://localhost:3000/public/components/angular/angular.min.js:198:426)
    at Object.<anonymous> (http://localhost:3000/public/components/angular/angular.min.js:108:188)
    at l.$get.l.$digest (http://localhost:3000/public/components/angular/angular.min.js:123:401)
    at l.$get.l.$apply (http://localhost:3000/public/components/angular/angular.min.js:126:471)
    at http://localhost:3000/public/components/angular/angular.min.js:139:187
    at e (http://localhost:3000/public/components/angular/angular.min.js:40:339)
    at http://localhost:3000/public/components/angular/angular.min.js:44:375
TypeError: Cannot read property 'replace' of undefined
    at a.$inject (http://localhost:3000/public/vendor/ng-admin/ng-admin.min.js:4:5622)
    at http://localhost:3000/public/components/angular/angular.min.js:194:11
    at l.$get.xa.(anonymous function) [as value] (http://localhost:3000/public/components/angular/angular.min.js:59:175)
    at hb.functionCall (http://localhost:3000/public/components/angular/angular.min.js:198:426)
    at Object.<anonymous> (http://localhost:3000/public/components/angular/angular.min.js:108:188)
    at l.$get.l.$digest (http://localhost:3000/public/components/angular/angular.min.js:123:401)
    at l.$get.l.$apply (http://localhost:3000/public/components/angular/angular.min.js:126:471)
    at http://localhost:3000/public/components/angular/angular.min.js:139:187
    at e (http://localhost:3000/public/components/angular/angular.min.js:40:339)
    at http://localhost:3000/public/components/angular/angular.min.js:44:375
```

**Comment by fzaninotto** [comment]
Yep, I c

**Comment by cvlmtg** [comment]
ok. btw I'm playing a bit with a custom directive, and I noticed that in the link function, the scope.entry.values objects doesn't contain just the entity values, but a lots of methods, including (guess what :) a method named "head". is this supposed to be correct?

![schermata 2015-02-02 alle 23 05 36](https://cloud.githubusercontent.com/assets/6401008/6010179/ad0b378a-ab30-11e4-90c9-306461725670.png)

**Comment by fzaninotto** [comment]
You're right, there is something wrong. It's like `values` gets a copy of the Restangular object... I'll dig deeper.

**Comment by cvlmtg** [comment]
thanks :)

**Comment by jeromemacias** [comment]
@fzaninotto Isn't be fixed with https://github.com/marmelab/admin-config/pull/20 ?

**Comment by fzaninotto** [comment]
I don't see how. Restangular erases data before we can read it.

**Comment by jpetitcolas** [comment]
On last master version, this bug doesn't seem to happen anymore. Yet, an error is displayed in the console:

```
angular.min.js:108 TypeError: safe.match is not a function
    at taSanitize (textAngular.js:398)
    at Array._sanitize (textAngular.js:1286)
    at angular.min.js:271
    at n.$digest (angular.min.js:132)
    at angular.min.js:135
    at e (angular.min.js:43)
    at angular.min.js:46
```
