### ISSUE TITLE
TypeError: nga.dashboard is not a function

### ISSUE THREAD

**Issue by karantan** [marmelab/ng-admin#523]
I integrated ng-admin and it works just fine. I have tested most features and they work nicely. But dashboard is breaking my app. It gives me this error:
```
Uncaught Error: [$injector:modulerr] Failed to instantiate module assetsApp due to:
TypeError: nga.dashboard is not a function
    at http://127.0.0.1:1337/scripts/admin.js:51:25
    at Object.invoke (http://127.0.0.1:1337/bower_components/angular/angular.js:4443:17)
    at runInvokeQueue (http://127.0.0.1:1337/bower_components/angular/angular.js:4349:35)
    at http://127.0.0.1:1337/bower_components/angular/angular.js:4358:11
    at forEach (http://127.0.0.1:1337/bower_components/angular/angular.js:336:20)
    at loadModules (http://127.0.0.1:1337/bower_components/angular/angular.js:4339:5)
    at createInjector (http://127.0.0.1:1337/bower_components/angular/angular.js:4265:11)
    at doBootstrap (http://127.0.0.1:1337/bower_components/angular/angular.js:1621:20)
    at bootstrap (http://127.0.0.1:1337/bower_components/angular/angular.js:1642:12)
    at angularInit (http://127.0.0.1:1337/bower_components/angular/angular.js:1536:5)
http://errors.angularjs.org/1.4.1/$injector/modulerr?p0=assetsApp&p1=TypeEr…2F%2F127.0.0.1%3A1337%2Fbower_components%2Fangular%2Fangular.js%3A1536%3A5)
```

I am using angular 1.4 and ng-admin 0.7

**Comment by fzaninotto** [comment]
The build files need updating, ping @jonathan

**Comment by jpetitcolas** [comment]
Build files updated on master. @karantan, can you try again?

**Comment by karantan** [comment]
great works now!  thank you!

P.S. I think this is my new favorite module  :+1:  Keep on the good work
