### ISSUE TITLE
js error after use updateMethod('PATCH')

### ISSUE THREAD

**Issue by shikelong** [marmelab/ng-admin#559]
I use `updateMethod` to change my update verb to `patch`.

```javascript
 doctor.updateMethod('PATCH');
```

when I update some data.and click on the `save update` button.

there is a error and no request be send.

```javascript
TypeError: W.resource(...)[E] is not a function
    at Object.T (http://localhost:8888/vendor.js:46:18518)
    at Object.F (http://localhost:8888/vendor.js:46:19109)
    at e.updateOne (http://localhost:8888/vendor.js:18:3773)
    at t.a.value (http://localhost:8888/vendor.js:15:29877)
    at n.submitEdition (http://localhost:8888/vendor.js:17:23359)
    at mi.functionCall (http://localhost:8888/vendor.js:27:11541)
    at ao.(anonymous function).r.compile.n.on.i (http://localhost:8888/vendor.js:27:18065)
    at p.e.$get.p.$eval (http://localhost:8888/vendor.js:26:1985)
    at p.e.$get.p.$apply (http://localhost:8888/vendor.js:26:2211)
    at HTMLFormElement.<anonymous> (http://localhost:8888/vendor.js:27:18117)

```

Regards.

**Comment by shikelong** [comment]
```javascript

 e.prototype.updateOne = function(e, t, n, r) {
            var i = this.Restangular.oneUrl(t, n)
              , o = r ? i.customOperation(r, null , {}, {}, e) : i.customPUT(e);  //error line
            return o.then(function(e) {
                return e.data
            }
            )
        }

```

**Comment by shikelong** [comment]
oh.  the right way usage is `entry.updateMethod('patch')`
restangular object has not a a property named `PATCH`

**Comment by magedhennawy** [comment]
wait what do you mean by your solution

**Comment by albogdano** [comment]
I had the same issue. @magedhennawy the `entry.updateMethod('patch')` - the method name should be lowercase. The docs are a bit misleading as they show the method name in uppercase.

**Comment by fzaninotto** [comment]
Could you open a PR to fix the docs?

**Comment by albogdano** [comment]
:+1: PR created
