### ISSUE TITLE
infinitePagination causes ReferenceError

### ISSUE THREAD

**Issue by toxsick** [marmelab/ng-admin#572]
Hello,

when I use .infinitePagination(true) it causes a ReferenceError error when a new page is loaded:
```
ReferenceError: dataStore is not defined
    at http://localhost:3000/bower_components/ng-admin/build/ng-admin.min.js:17:24483
    at Array.map (native)
    at http://localhost:3000/bower_components/ng-admin/build/ng-admin.min.js:17:24467
    at processQueue (http://localhost:3000/bower_components/angular/angular.js:13300:27)
    at http://localhost:3000/bower_components/angular/angular.js:13316:27
    at Scope.$get.Scope.$eval (http://localhost:3000/bower_components/angular/angular.js:14555:28)
    at Scope.$get.Scope.$digest (http://localhost:3000/bower_components/angular/angular.js:14371:31)
    at Scope.$get.Scope.$apply (http://localhost:3000/bower_components/angular/angular.js:14660:24)
    at http://localhost:3000/bower_components/angular/angular.js:14950:22
    at completeOutstandingRequest (http://localhost:3000/bower_components/angular/angular.js:4940:10)(anonymous function) @ angular.js:11707$get @ angular.js:8628processQueue @ angular.js:13308(anonymous function) @ angular.js:13316$get.Scope.$eval @ angular.js:14555$get.Scope.$digest @ angular.js:14371$get.Scope.$apply @ angular.js:14660(anonymous function) @ angular.js:14950completeOutstandingRequest @ angular.js:4940(anonymous function) @ angular.js:5328
```

The request is successful, but the data is not shown in the listView.

I can reproduce this with the [ng-admin-demo](https://github.com/marmelab/ng-admin-demo) when I enable infinitePagination for the comment.listView.

Help?!

regards
Hannes

**Comment by fzaninotto** [comment]
I confirm that I can reproduce the issue. Investigating.

**Comment by fzaninotto** [comment]
Fixed now, sorry for the regression.
