### ISSUE TITLE
webpack fails to load js spread operator

### ISSUE THREAD

**Issue by lucval** [marmelab/ng-admin#798]
Hi,
when trying to build master, "Unexpected token" errors are raised when loading the Column and Button directives (ma*Button.js).
For all cases the error is caused by the spread operator used at this line:
```
var stateParams = entityName == $state.params.entity ? { ...$state.params } : {};
```

Anybody else experencing this?

**Comment by fzaninotto** [comment]
Which version of babel do you have installed?

**Comment by lucval** [comment]
```
├─┬ babel@4.7.16
│ ├── acorn-babel@0.11.1-38
│ ├─┬ regenerator-babel@0.8.13-2
├─┬ babel-core@5.4.7
├─┬ babel-loader@5.1.3
├─┬ grunt-babel@4.0.0
│ └─┬ babel-core@4.7.16
│   ├── acorn-babel@0.11.1-38
│   ├─┬ regenerator-babel@0.8.13-2
├── karma-babel-preprocessor@4.0.1 extraneous
```
For completeness here is one of the error traces (the other ones are basically identical):
```
ERROR in ./src/javascripts/ng-admin/Crud/button/maEditButton.js
Module build failed: SyntaxError: /home/luca/ng-admin/node_modules/ng-annotate-loader/loader.js!/home/luca/ng-admin/src/javascripts/ng-admin/Crud/button/maEditButton.js: Unexpected token (19:69)
  17 |         link: function (scope, element, attrs) {
  18 |             var entityName = scope.entity() ? scope.entity().name() : attrs.entityName;
> 19 |             var stateParams = entityName == $state.params.entity ? { ...$state.params } : {};
     |                                                                      ^
  20 |             stateParams.entity = entityName;
  21 |             stateParams.id = scope.entry().identifierValue;
  22 |             scope.stateParams = stateParams;
    at Parser.pp.raise (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/location.js:73:13)
    at Parser.pp.unexpected (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/parseutil.js:87:8)
    at Parser.pp.parseIdent (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:750:10)
    at Parser.pp.parsePropertyName (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:637:120)
    at Parser.pp.parseObj (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:585:12)
    at Parser.pp.parseExprAtom (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:363:19)
    at Parser.parseExprAtom (/home/luca/ng-admin/node_modules/acorn-jsx/inject.js:373:24)
    at Parser.pp.parseExprSubscripts (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
    at Parser.pp.parseExprOps (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:155:19)
    at Parser.pp.parseMaybeConditional (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:138:19)
    at Parser.pp.parseMaybeAssign (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
    at Parser.pp.parseMaybeConditional (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:143:28)
    at Parser.pp.parseMaybeAssign (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
    at Parser.pp.parseVar (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/statement.js:438:24)
    at Parser.pp.parseVarStatement (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/statement.js:332:8)
    at Parser.pp.parseStatement (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/statement.js:87:19)
    at Parser.parseStatement (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/plugins/flow.js:636:22)
    at Parser.pp.parseBlock (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/statement.js:387:21)
    at Parser.pp.parseFunctionBody (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:693:22)
    at Parser.parseFunctionBody (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/plugins/flow.js:624:20)
    at Parser.pp.parseFunction (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/statement.js:465:8)
    at Parser.pp.parseExprAtom (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:368:19)
    at Parser.parseExprAtom (/home/luca/ng-admin/node_modules/acorn-jsx/inject.js:373:24)
    at Parser.pp.parseExprSubscripts (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:217:19)
    at Parser.pp.parseMaybeUnary (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:199:19)
    at Parser.pp.parseExprOps (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:155:19)
    at Parser.pp.parseMaybeConditional (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:138:19)
    at Parser.pp.parseMaybeAssign (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:106:19)
    at Parser.pp.parseObjPropValue (/home/luca/ng-admin/node_modules/babel-core/lib/acorn/src/expression.js:599:62)
 @ ./src/javascripts/ng-admin/Crud/CrudModule.js 80:37-69
```

So since ng-annotate might be the culprit:
```
├─┬ grunt-ng-annotate@0.10.0
│ └─┬ ng-annotate@0.15.4
├─┬ ng-annotate-loader@0.0.2
│ ├─┬ ng-annotate@0.15.4
├─┬ ng-annotate-webpack-plugin@0.1.2
│ ├─┬ ng-annotate@0.9.11
```

Of course before building I have run a make install and everything looked fine.

**Comment by fzaninotto** [comment]
I made a fresh install and didn't have any problem. But it seems that I have different versions of babel installed than you, especially babel-core and babel-loader - despite using the same `package.json`:

```
> npm ls | grep babel
├─┬ babel@4.7.16
│ ├── acorn-babel@0.11.1-38
│ ├─┬ regenerator-babel@0.8.13-2
├─┬ babel-core@5.8.34
│ ├── babel-plugin-constant-folding@1.0.1
│ ├── babel-plugin-dead-code-elimination@1.0.2
│ ├── babel-plugin-eval@1.0.1
│ ├── babel-plugin-inline-environment-variables@1.0.1
│ ├── babel-plugin-jscript@1.0.4
│ ├── babel-plugin-member-expression-literals@1.0.1
│ ├── babel-plugin-property-literals@1.0.1
│ ├── babel-plugin-proto-to-assign@1.0.4
│ ├── babel-plugin-react-constant-elements@1.0.3
│ ├── babel-plugin-react-display-name@1.0.3
│ ├── babel-plugin-remove-console@1.0.1
│ ├── babel-plugin-remove-debugger@1.0.1
│ ├── babel-plugin-runtime@1.0.7
│ ├─┬ babel-plugin-undeclared-variables-check@1.0.2
│ ├── babel-plugin-undefined-to-void@1.1.6
├─┬ babel-loader@5.4.0
├─┬ grunt-babel@4.0.0
│ └─┬ babel-core@4.7.16
│   ├── acorn-babel@0.11.1-38
│   ├─┬ regenerator-babel@0.8.13-2
```

Could you try removing your `node_modules` files, clearing the npm cache, and run `make install` again?

Also, which version of node.js are you running? Please use at least Node 4.1.0.

**Comment by lucval** [comment]
as expected updating babel-core solved the issue

**Comment by wangwy** [comment]
I use node 6.10.1 and same package.json, when trying to build master, "Unexpected token" errors are raised when loading the Column and Button directives (ma*Button.js).
