### ISSUE TITLE
Error on show view vs. edit view

### ISSUE THREAD

**Issue by jamespsterling** [marmelab/ng-admin#901]
I'm getting an error with the following field on 'show view' only. Works just fine in 'edit view'. Any idea what I'm doing wrong?

```
TypeError: Cannot read property 'updated_date' of undefined
    at p.n.getInput (maField.js:25)
    at p.n.fieldHasValidation (maField.js:36)
    at p.n.getFieldValidationClass (maField.js:46)
    at Object.get (angular.js:12474)
    at p.$digest (angular.js:14404)
    at angular.js:14609
    at o (angular.js:4940)
    at angular.js:5328
```

```
    user.editionView()
        .title('Edit User')
        .fields(
        nga.field('updated_date', 'datetime')
            .label('Updated Date')
            .format('medium')
            .editable(false)
            .template(maFieldTemplate('updated_date'), true),
            user.creationView().fields()
        );

    user.showView()
        .title('User')
        .fields(user.editionView().fields());
```

```
function maFieldTemplate(value)
{
    return '<ma-field ng-if="entry.values.' + value +
            ' !== undefined && entry.values.' + value +
            ' !== null && entry.values.' + value +
            ' !== \'0\'" field="::field" value="entry.values[field.name()]" entry="entry" entity="::entity" form="formController.form" datastore="::formController.dataStore"></ma-field>';
}
```

**Comment by cfatt10** [comment]
When I've gotten errors like this it was because something was null. In my case it didn't affect how ng-admin worked, but my stack trace was also different than yours. Are there any symptoms associated with the error (e.g. the page won't load, unexpected behavior, etc?)

**Comment by jamespsterling** [comment]
Works fine, just lots of ugly errors in the console. I'd like to find a way to suppress them. Something is definitely null and blank in my database.

**Comment by fzaninotto** [comment]
It's possible that the first time Angular.js renders the page, the data isn't fully fetched - hence the alert on a null value. You should actually test for null values.

**Comment by jamespsterling** [comment]
That's not the case here. Angular is loaded, then ng-admin and it's dependencies then the data is fetched. The problem is null or empty references for my reference-typed fields.

Anyway, shouldn't ng-admin gracefully handle null or empty reference pointers?

**Comment by jamespsterling** [comment]
And furthermore, this is my template method which works great in editView, but in showView is a mess. Is there a better template to use for showView?

```
function maFieldTemplate(value)
{
    return '<ma-field ng-if="entry.values.' + value + ' !== undefined ' +
            ' && entry.values.' + value + ' !== null ' +
            ' && entry.values.' + value + ' !== \'0\' ' +
            ' && entry.values.' + value + ' !== \'\'" ' +
            ' field="::field" value="entry.values[field.name()]" entry="entry" entity="::entity" form="formController.form" datastore="::formController.dataStore"></ma-field>';
}
```

**Comment by fzaninotto** [comment]
It doesn't make sense to output a `<ma-field>` in a show view. It carries edition logic (even if you make it non editable). Use a `<ma-column>` instead.

**Comment by jamespsterling** [comment]
Thanks for the tip!

One more question, I'm getting and error trying ma-column. Any idea what I'm doing wrong?

```
TypeError: Cannot read property 'isReadOnly' of undefined
    at o (http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:15:25168)
    at link (http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:15:26021)
    at http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:25:3694
    at ae (http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:25:3751)
    at w (http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:24:29868)
    at s (http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:24:25689)
    at http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:24:25185
    at F.i (http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:24:26180)
    at c (http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:24:28361)
    at Object.fn (http://classcode.corp.york-claims.com/scripts/vendor/ng-admin.min.js:27:18314) <ma-column ng-if="entry.values.updated_date !== undefined  &amp;&amp; entry.values.updated_date !== null  &amp;&amp; entry.values.updated_date !== '0'  &amp;&amp; entry.values.updated_date !== ''" field="::field" value="entry.values[field.name()]" entry="entry" entity="::entity" form="formController.form" datastore="::formController.dataStore">
```

**Comment by jamespsterling** [comment]
@fzaninotto can you shed any light on the issue above?

**Comment by taraujoz** [comment]
I'm getting a similar error: 

> maReferenceField.js:47 Uncaught (in promise) TypeError: Cannot read property 'values' of undefined


It started after adding _remoteComplete_ to a field:
```
nga.field('address.city', 'reference')
                .targetEntity(admin.getEntity('cities'))
                .targetField(nga.field('name'))
                .remoteComplete(true, {
                    refreshDelay: 300,
                    searchQuery: function(search) { return { search: search }; }
                }),
```

While using, the fail occurs immediately after I select an item in a combobox.

Any ideias why it is happening and how to fix?

**Comment by jamespsterling** [comment]
@taraujoz having the same issue currently. Are you transforming your data at all in ```RestangularProvider.addResponseInterceptor(...)``` method?
